apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-app
  namespace: mynamespace
  labels:
    app: dotnetdemo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo-app
  template:
    metadata:
      labels:
        app: dotnetdemo-app
    spec:
      containers:
      - name: dotnetdemo-app
        image: mydockerimage007.azurecr.io/dotnetapp:1.0.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: surya