apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-app
  namespace: ipl
  labels:
    app: dotnetdemo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo-app
  template:
    metadata:
      labels:
        app: dotnetdemo-app
    spec:
      containers:
      - name: dotnetdemo-app
        image: viratkohli.azurecr.io/hyderabad:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: cricket