apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo-app
  namespace: ipl
spec:
  selector:
    app: dotnetdemo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000