apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo-app
  namespace: prasai
spec:
  selector:
    app: dotnetdemo-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000